extends Node

signal select_color
signal update_color_buttons
signal update_ready_players_lobby
signal start_game

signal get_tile_position
signal set_tile_position

signal select_troop
signal select_tile

signal show_movement_spaces
signal show_placement_spaces
signal reset_tile_indicators
signal plan_troop_move
signal undo_move
signal mortar_firing_mode
signal mortar_movement_mode
signal update_ready_players_board

signal get_attack_lists
signal check_if_attacks_ready

signal get_round_resources
signal troop_defeated
signal move_troop_tabs
signal update_troop_info

signal craft_troop
